// Generated by Code/tools/bake_theme.py — do not edit by hand.
//
// Placement constants come from the rasterizer, not from hand-measuring
// the design: each cropped asset records where its top-left corner sits
// on the 320x240 panel, so re-baking a changed design moves the widgets
// automatically.
#ifndef CubeThemeAssets_h
#define CubeThemeAssets_h

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

// 320x240, 153600 bytes
extern const lv_image_dsc_t theme_bg;
#define THEME_BG_X 0
#define THEME_BG_Y 0
#define THEME_BG_W 320
#define THEME_BG_H 240

// 255x194, 148410 bytes
extern const lv_image_dsc_t theme_band_fill;
#define THEME_BAND_FILL_X 33
#define THEME_BAND_FILL_Y 23
#define THEME_BAND_FILL_W 255
#define THEME_BAND_FILL_H 194

// 255x196, 149940 bytes
extern const lv_image_dsc_t theme_band_edge;
#define THEME_BAND_EDGE_X 33
#define THEME_BAND_EDGE_Y 22
#define THEME_BAND_EDGE_W 255
#define THEME_BAND_EDGE_H 196

// 85x145, 36975 bytes
extern const lv_image_dsc_t theme_next_frame;
#define THEME_NEXT_FRAME_X 194
#define THEME_NEXT_FRAME_Y 51
#define THEME_NEXT_FRAME_W 85
#define THEME_NEXT_FRAME_H 145

// 167x48, 24048 bytes
extern const lv_image_dsc_t theme_bar_unsel;
#define THEME_BAR_UNSEL_X 0
#define THEME_BAR_UNSEL_Y 0
#define THEME_BAR_UNSEL_W 167
#define THEME_BAR_UNSEL_H 48

// 167x48, 24048 bytes
extern const lv_image_dsc_t theme_bar_sel;
#define THEME_BAR_SEL_X 0
#define THEME_BAR_SEL_Y 0
#define THEME_BAR_SEL_W 167
#define THEME_BAR_SEL_H 48

// 48x48, 6912 bytes
extern const lv_image_dsc_t theme_orb;
#define THEME_ORB_X 0
#define THEME_ORB_Y 0
#define THEME_ORB_W 48
#define THEME_ORB_H 48

// 16x16, 768 bytes
extern const lv_image_dsc_t theme_comma;
#define THEME_COMMA_X 0
#define THEME_COMMA_Y 0
#define THEME_COMMA_W 16
#define THEME_COMMA_H 16

// 56x56, 9408 bytes
extern const lv_image_dsc_t theme_sonar;
#define THEME_SONAR_X 0
#define THEME_SONAR_Y 0
#define THEME_SONAR_W 56
#define THEME_SONAR_H 56

// 70x112, 23520 bytes
extern const lv_image_dsc_t theme_pane;
#define THEME_PANE_X 0
#define THEME_PANE_Y -7
#define THEME_PANE_W 70
#define THEME_PANE_H 112

// 4x60, 720 bytes
extern const lv_image_dsc_t theme_next_label;
#define THEME_NEXT_LABEL_X 1
#define THEME_NEXT_LABEL_Y 6
#define THEME_NEXT_LABEL_W 4
#define THEME_NEXT_LABEL_H 60

extern const lv_font_t lv_font_bar_12;   // 12px, bar labels, info rows
extern const lv_font_t lv_font_head_16;   // 16px, operation headlines
extern const lv_font_t lv_font_prev_9;   // 9px, preview pane list
extern const lv_font_t lv_font_title_13;   // 13px, screen title
extern const lv_font_t lv_font_desc_11;   // 11px, description bar

// Total image flash: 578349 bytes (564.8 KB)
#define THEME_IMAGE_BYTES 578349

#ifdef __cplusplus
}
#endif

#endif // CubeThemeAssets_h
