// Generated by Code/tools/bake_theme.py — do not edit by hand.
//
// Baked assets are large and read-only, so they belong in flash. On Teensy 4.x
// PROGMEM keeps them there (flash is memory-mapped, so LVGL can read them in
// place); on the desktop simulator there is no such attribute and the define
// collapses to nothing. Same idiom the kociemba cache tables use.
#ifndef CubeThemeProgmem_h
#define CubeThemeProgmem_h

#include <lvgl.h>

#if defined(__has_include)
#  if __has_include(<avr/pgmspace.h>)
#    include <avr/pgmspace.h>
#  endif
#endif

#ifndef PROGMEM
#  define PROGMEM
#endif

#endif // CubeThemeProgmem_h
